[package]
name = "spreadsheet_rust"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "spreadsheet"
path = "src/main.rs"

[dependencies]
yew = { version = "0.21", features = ["csr"] }

[dependencies.wasm-bindgen]
version = "0.2"

[dependencies.web-sys]
version = "0.3"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
